### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by enumag** [07th-mod/meakashi#10]
Just a small issue. It seems we're missing part of the text [here](https://github.com/07th-mod/meakashi/blob/master/Update/_meak_021_2.txt#L1643-L1645). The [voice](https://www.dropbox.com/s/5qr5q6dq36ds2yv/150602109.ogg?dl=0) is slightly longer.

**Comment by ItaloKnox** [comment]
I almost got the issue wrong, there's actually a very small particle missing in the japanese text but it doesn't change anything, so I was going to post about it.

So, about the translation, the missing part should be something like ``You always look at me with those [cunning, crafty] eyes!!``. Just take your pick of one of the many words that could fit in there. I just woke up so my english is still quite rusty to find something good.

**Comment by enumag** [comment]
@ItaloKnox Thanks. Is this ok? `You were always jealous of me. Always looking at me with those foxy eyes!!`

**Comment by enumag** [comment]
ping @ItaloKnox I'd like to close this.

**Comment by ItaloKnox** [comment]
I'm pretty sure I left a comment here but maybe I didn't send before closing. Yep, it looks good enough!
