### ISSUE TITLE
Date in English text written in ISO-8601

### ISSUE THREAD

**Issue by ddawson** [07th-mod/meakashi#11]
In Scripts/_meak_tips_21.txt line 121 (line 114 in your version, or 142 in adv-mode and adv-mode-auto branches), MG wrote the date as "1983-06-01T11:00:00.000Z" instead of (right-justified) "June, 1983" for some unknown reason. I emailed them a report, but I understand you accept issues like this. So, here you are.

**Comment by ItaloKnox** [comment]
Hey, @enumag, you might want to take a look at this. I haven't read Meakashi yet so I don't know much about the specifics.

**Comment by enumag** [comment]
Fixed. I removed the right-justification too because it doesn't work well with ADV-mode.

Thanks for reporting.
