### ISSUE TITLE
"PlaySE..." instead of text

### ISSUE THREAD

**Issue by nocturne32** [07th-mod/meakashi#12]
Finally got to play this chapter but after meeting Satoshi sitting on a swing, I bumped upon this:
![image](https://user-images.githubusercontent.com/18268621/27511974-7f04a9f4-5932-11e7-8fb4-37ceca1f7ad9.png)
I don't really mind, but I thought that I could share this, so it could be fixed or something.
Maybe it is fixed already. I have the version from 6th May. I'm lazy to update.

**Comment by ItaloKnox** [comment]
That's correct, the issue seems to be already fixed in the latest version. 😄
