### ISSUE TITLE
Sprite names

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/meakashi#15]
@Grelo 
I need to make sprite name diff list in Meakashi for lip-sync(LipSync need to use ps3 names).

But Meakashi have QA and AA and PS3 sprite name and these are almost closed mouse one, so I'm confusing.

Could you remember how did you replace them?

**Comment by Grelo** [comment]
@P-Chang
I was making them 1 by 1 and used both new AA PS3 images and images from older chapters and if something was contradicting with the name i usually added `-` `--` etc, mostly for weather variations. But there is no rule like `-` is sunset and `--` is night. 
They could be shuffled.
This will need maual treatment and maybe even image by image...unfortunatelly.

**Comment by P-Chang** [comment]
https://github.com/07th-mod/higurashi-patch-compiler/issues/15#issuecomment-357542284
