### ISSUE TITLE
[Help wanted] Meakashi LipSync update

### ISSUE THREAD

**Issue by enumag** [07th-mod/meakashi#18]
**Anyone can help with this issue. Even if you're just random fan who wants to help us.**

To add the LipSync feature for Meakashi we need to remake the current graphics patch. To keep this issue simple I won't go into details what's so bad about the current patch, why we need to change it and how is the old patch different than the question arcs patches (ask me on Discord if you're curious and I'll explain). Instead I'll just write guidelines how to make what we need.

1. Download and unpack [Meakashi CGAlt sprites](https://github.com/07th-mod/resources/releases/download/Nipah/Meakashi-CGAlt.zip).
2. Download and unpack [Meakashi CG archive](https://github.com/07th-mod/resources/releases/download/Nipah/Meakashi-CG.zip).
3. Download and unpack [PS3 sprites](https://github.com/07th-mod/resources/releases/download/Nipah/HigurashiPS3-Sprites.zip).
4. Open the CGAlt Meakashi directory you just downloaded.
5. Select a character and post a note here that you're working on that character.
6. Create an empty excel table (or open office / libre office / google docs equivalent). You'll need 4 columns: current name, weather variant, zoom, PS3 name
7. For each sprite of that character do the following:
    1. Copy the name of the sprite and paste it to a new line of the excel table - first column.
    2. To the second column write which weather variant the sprite is: normal/sunset/night.
    3. To the third column write whether the sprite is zoomed or not: yes/no.
    4. Open the Meakashi CG directory and find the sprite with the same name.
    5. Open the PS3 directory and find the same sprite (disregard weather). Most of the time the name will be quite similar.
    6. The sprite you just found in the PS3 directory has 3 variants with `_0`, `_1` and `_2` suffix. Out of these three select the one with facial expression closest to the sprite you started with (the one in CGAlt directory).
        - Not the one in CG directory!! All of those have closed mouth which is wrong. Many sprites in CGAlt directory don't have their mouth closed.
    7. Copy the name of the selected PS3 sprite to the fourth column in the excel table.
    8. Save the file so that you don't accidently lose your work and continue to the next sprite.
8. Upload the finished excel file and send a link to this issue.
9. **Thank you very much! You're the best!**

Example:

Let's take one of the sprites for Rika-chama.

CGAlt sprite `ri2_WaraiA1_0-.png`:

![ri2_waraia1_0-](https://user-images.githubusercontent.com/539462/37877138-b8ddc042-3056-11e8-9e8a-de661ac5071d.png)

Based on this sprite we add this to the excel:

| Current name | weather | zoom | PS3 name |
|---|---|---|---|
| ri2_WaraiA1_0-.png | sunset | no |   |

Matching CG sprite `ri2_WaraiA1_0-.png`:

![ri2_waraia1_0-](https://user-images.githubusercontent.com/539462/37877179-52655d92-3057-11e8-9c31-f3e5e59210d6.png)

PS3 sprite `ri2_WaraiA1_0.png`:

![ri2_waraia1_0](https://user-images.githubusercontent.com/539462/37877193-80aff860-3057-11e8-8ce7-de1af911e92b.png)

Based on facial expression of the CGAlt sprite the correct PS3 sprite is `ri2_WaraiA1_1.png`:

![ri2_waraia1_1](https://user-images.githubusercontent.com/539462/37877197-965e7e52-3057-11e8-89f4-852f0dcec38f.png)

So we add it to the excel:

| Current name | weather | zoom | PS3 name |
|---|---|---|---|
| ri2_WaraiA1_0-.png | sunset | no | ri2_WaraiA1_1.png |

It does not matter if you omit the .png extensions, use just y/n instead of yes/no or -/s/n instead of normal/sunset/night. So this is also completely fine:

| Current name | weather | zoom | PS3 name |
|---|---|---|---|
| ri2_WaraiA1_0-| s | n | ri2_WaraiA1_1|

**Comment by Petsnew** [comment]
Alright, I'll be working on Rika.

**Comment by Petsnew** [comment]
Gonna work on Satoko now.

**Comment by Petsnew** [comment]
Keiichi

**Comment by irlPM** [comment]
I'm going with mion.

**Comment by irlPM** [comment]
Satoshi

**Comment by irlPM** [comment]
Shion

**Comment by irlPM** [comment]
Takano

**Comment by irlPM** [comment]
Tomitake

**Comment by irlPM** [comment]
Curry Maniac

**Comment by irlPM** [comment]
Sonozaki Mother
[Sonozaki Mother.xlsx](https://github.com/07th-mod/meakashi/files/1858525/Sonozaki.Mother.xlsx)

**Comment by irlPM** [comment]
Coach

**Comment by irlPM** [comment]
Kasai
[Kasai.xlsx](https://github.com/07th-mod/meakashi/files/1858550/Kasai.xlsx)

**Comment by irlPM** [comment]
Oishi

**Comment by irlPM** [comment]
Rena

**Comment by enumag** [comment]
@Petsnew @irlPM Thank you! I'll update my script to use these.
