### ISSUE TITLE
Kasai appears zoomed

### ISSUE THREAD

**Issue by Mikulovers** [07th-mod/meakashi#20]
![bild](https://user-images.githubusercontent.com/39219285/40203592-f8ee3132-5a25-11e8-9b35-d9de7ed38d2c.png)
Right before this line Kasai's model got zoomed in without any change in expression despite looking normal up until then..

**Comment by idealpersona** [comment]
Relevant line in the script: https://github.com/07th-mod/meakashi/blob/84c59f383fbad78edb3175a4abe3683d5ac88941/Update/_meak_013.txt#L693

**Comment by idealpersona** [comment]
With the recent prerelease update scripts this seems to be fixed.  This includes changing from ChangeBustshot to ModDrawCharacter and fixing the asset path.
