### ISSUE TITLE
CG shows Rena staring at Keiichi instead of Shiion

### ISSUE THREAD

**Issue by idealpersona** [07th-mod/meakashi#21]
`CG/scene/002a.png` is used in Meakashi, but is from Onikakushi.  Rena is talking to Shiion but the CG shows her staring at Keiichi.  @Grelo pointed out this needs to be zoomed in to show only rena's face.  I'm not sure whether this means there is a separate CG for that or we need to script a zoom on the existing CG for that.

Grelo or @enumag do you know which is the correct answer for that?

**Comment by enumag** [comment]
The new graphics patch was mostly compiled automatically so this one is wrong. The previous patch used zoom to show only Reina (variant with Shion does not exist as far as I know). I'm not exactly sure how it was on PS3 though.

Easy fix is to just replace it with zoomed version. I think that's good enough at least until orian gets to Meakashi.

**Comment by Grelo** [comment]
PS3 used the exact same zooked face like image we used. I made it exactly as PS3.

**Comment by DoctorDiablo** [comment]
If we want to handle the zoom in the script, the system is capable of it.  I recently did something like that [here](https://github.com/07th-mod/higurashi-console-arcs/blob/master/Update/tara_003.txt#L1183) in the console arcs.  The 3rd, 4th, and 5th parameters in DrawBustshot are the x/y/z coordinates.  Making the z value a larger negative number zooms in more, and tweaking the x/y coordinates can shift it so it zooms in on the right location.

**Comment by Grelo** [comment]
Still surprised this is not fixed yet as there are more issues like this. For someone this could be definitely "game breaking".

**Comment by orian34** [comment]
handled
