### ISSUE TITLE
Missing voices during ending text scroll

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/meakashi#26]
@irlPM pointed out that Shion's speech at the end of Meakashi has voice acting in the ps3 version, but not in our mod.  This is while the text in meakasi_list.png is scrolling across the screen.

I found the voice files for this, they're from s06\06\meashi91001.ogg to 016.ogg.  We should be able to add these in, but it might be tricky to get the voices to play at the proper timing as the text is scrolling.

**Comment by irlPM** [comment]
We won't do as the text is scrolling. I'll remake each sentence as a single image just like sui. But italo said we shouldn't release anything until tsumi so I'm waiting.

**Comment by ItaloKnox** [comment]
You know... you can make it and we can release it as a cumulative update as we've been doing it since always. You don't have to halt progress just because we're toning down the number of minor updates.

**Comment by irlPM** [comment]
Okay sure, I'll be doing it then. Thanks for the help Doctor!

**Comment by irlPM** [comment]
Okay sure, I just thought a minor update like this won't be released until tsumi is out so I just delayed a little. I'll be doing it then. Thanks for the help Doctor!

**Comment by DoctorDiablo** [comment]
The text is actually the same aside from some extremely minor differences (like souiukoto instead of kouiukoto and 1 instead of the kanji for 1), so I think we're good to use the existing translation.  The problem is that the voice files are out of order.

Play them in this order, and it'll line up properly with the text: 1, 2, 3, 4, 5, **10**, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16

**Comment by enumag** [comment]
@irlPM @DoctorDiablo This can be closed now, right? (see #27)

**Comment by irlPM** [comment]
Yes, I'll close it.
