### ISSUE TITLE
minor Japanese audio transcription needed

### ISSUE THREAD

**Issue by Norgus** [07th-mod/meakashi#28]
https://github.com/07th-mod/meakashi/blob/ce5cbf41fd8e953652581c7692b2d313e0a012d6/Update/_zmeak_015_1_vm0x_n01.txt#L333

I've made a best effort with this line and included a translation I think makes sense, but there is one word/expression in there I can't tell what Keiichi is saying. Any Japanese speakers with a better ear than me?

**Comment by enumag** [comment]
For anyone trying to determine this, here is the voice: https://cdn.discordapp.com/attachments/384427950478589972/466351011334717441/150100058.ogg

**Comment by Norgus** [comment]
Oops, thanks for that!

**Comment by enumag** [comment]
ping @DoctorDiablo @ItaloKnox

**Comment by ItaloKnox** [comment]
You mean this ``（聞き取れず）``, right? Because I can hear everything else you transcribed. I'm also having a lot of trouble deciphering it. I even went as far as hearing ``not`` and ``and`` when said in katakana.

**Comment by MeeraMalhotra** [comment]
I took a look at the issue. I couldn't make out exactly what the word was and I looked a lot of different adaptations (PC, Matsuri, Sui), but the line has been changed and I couldn't find the original words.

To my knowledge the missing words must be (乗っ取らんとッ)

**Comment by Norgus** [comment]
2ba8bee844a13f75b5c49921c0261fec9331081a

Used your suggestion because it sounds about right, haven't changed the translation because it makes sense as it is and I'm not sure what this addition would change meaning wise (I don't really get it in context so might still be wrong?)
