### ISSUE TITLE
Downloading opening video issues

### ISSUE THREAD

**Issue by ShogunKitsune** [07th-mod/meakashi#29]
Hi,

It looks like all the Linux/Mac download links for the opening videos aren't working, the server returns a 404.
This also goes for the first (Onikakushi) download link for Windows.

**Comment by ItaloKnox** [comment]
Onikakushi is working, but I looked and it was Watanagashi that was broken. You are also correct about the 404 links for Linux/Mac. I did a small change in the filename and forgot to update the wiki.

It's fixed now, thanks for reporting it. Let me know if it works for you.

**Comment by ShogunKitsune** [comment]
Yeah, it is fixed, thanks!
