### ISSUE TITLE
Config Menu Issue (All chapters)

### ISSUE THREAD

**Issue by orian34** [07th-mod/meakashi#31]
I'm sorry for not noticing this before, but after checking on earlier chapters too, I saw there was something strange:
![image](https://user-images.githubusercontent.com/12663654/46524964-a4c1b380-c88a-11e8-94dc-5cab38a38c90.png)
As you can see, the "Updated" box is not like the others when it's selected, it is lacking the white border.(a comparison is done with the "On" "Off")

I also noticed the resolutions don't have the red indicator except for the fullscreen button when selected.(cf image)

I checked in Tatari and Hima and it was the same, so I will make the guess it's for all chapters.
I guess I really wasn't paying attention the 4 other times...

**Comment by enumag** [comment]
Yeah this is in all chapters and in vanilla too. We might not even be able to fix this on our side.

@Doddler Do you have some insight what's wrong here and how to fix it?
