### ISSUE TITLE
New Tip Picture

### ISSUE THREAD

**Issue by orian34** [07th-mod/meakashi#32]
![image](https://user-images.githubusercontent.com/12663654/46549236-98ad1480-c8d1-11e8-8845-7feb5a82221e.png)

Maybe we should edit the sentence to say "a new TIP"

**Comment by orian34** [comment]
actually, seems like several tips have the correct sentencing, so those ones should just have "a new TIP"

**Comment by enumag** [comment]
Tips screens were remade completely. For example here here is the relevant one.

![gettip_meak005](https://user-images.githubusercontent.com/539462/47265862-aba92100-d52e-11e8-9400-7ca75e28a03e.png)
