### ISSUE TITLE
Final List Picture Typos

### ISSUE THREAD

**Issue by orian34** [07th-mod/meakashi#36]
![image](https://user-images.githubusercontent.com/12663654/46589450-fc8a3580-caa9-11e8-8e2d-938b705ca99a.png)
I believe it's Oryou?

![image](https://user-images.githubusercontent.com/12663654/46589505-76222380-caaa-11e8-9da5-43612e5cedb4.png)
Hemorrhaging? 

Also, for "meaed2.png"
![image](https://user-images.githubusercontent.com/12663654/47111459-e9b6f400-d253-11e8-8f61-4341fdadbd8c.png)

EDIT by enumag: The line should end with `I can't possibly eat them all.` Also the quote at the beginning should be removed.

**Comment by enumag** [comment]
meaed2.png was changed to this. Do you think it's ok?

![meaed2](https://user-images.githubusercontent.com/539462/47265884-18242000-d52f-11e8-9cf9-48ebc4784886.png)

**Comment by orian34** [comment]
Is there a limit? Else the sentence is "I can't possibly eat them all!"

**Comment by enumag** [comment]
ping @irlPM

**Comment by enumag** [comment]
Here are the images that need to be edited:

- [meaed2](https://user-images.githubusercontent.com/539462/57157040-e0503c00-6ddf-11e9-9dec-77551137252d.png)
- [meak_staff_01](https://user-images.githubusercontent.com/539462/57157093-007ffb00-6de0-11e9-9f6b-c93b854140de.png)
