### ISSUE TITLE
Omake

### ISSUE THREAD

**Issue by orian34** [07th-mod/meakashi#38]
Just leaving it here in case, but shouldn't it be named "Extras" instead of omake? 
![image](https://user-images.githubusercontent.com/12663654/46888794-c958f500-ce61-11e8-9527-6cc1089cb798.png)

Especially considering that...
![image](https://user-images.githubusercontent.com/12663654/46888832-e8f01d80-ce61-11e8-926c-aaf1a5d2e5cb.png)

**Comment by ItaloKnox** [comment]
I think that happens just because it's the original menu for both languages, it's commonly named ``omake`` in every 07th Expansion release. We can change it or not, I don't think it makes that much of a difference.
