### ISSUE TITLE
BGM Heavily Saturated

### ISSUE THREAD

**Issue by orian34** [07th-mod/meakashi#39]
the BGM "higurashi_soundscape.ogg" has heavy saturation and is very likely not intended, because it rips my eardrums off trying to listen to it. 
I don't know the voodoo about audio files, so I'm asking @ItaloKnox  to see what can be done

**Comment by ItaloKnox** [comment]
Huh... do you mean the static or something? They kinda look intentional to me.

I have some studio work to do so I'm going to have access to iZotope RX 7, so I can try to make it more bearable, but I need some points of reference.

**Comment by orian34** [comment]
The start is a bit strange, especially around 00:19. But it's somewhat okish if you claim it's intentional.
There's a big chunk of really nice, then at around 02:51 it starts shredding the ears for around 9 seconds.
And afterwards, there's a saturated bit starting 03:14. Where it seems like my computer is dying at the end.

**Comment by ItaloKnox** [comment]
I went with what I have right here and this is what I got: https://transfer.sh/LXaOh/higurashi_soundscape.ogg

* applied some de-clip
* applied some heavy de-crackle

As you can see, there's no much you can do other than reduce the harshness just a little bit with some loss of detail. Your call.

**Comment by orian34** [comment]
Mh, maybe we could have some other opinions, but the second one is more bearable, yes.

**Comment by enumag** [comment]
Found a flac version of the song in one of my OST collections. Is it any better?

https://www.dropbox.com/s/lkroz2noz3g0oi0/01%20-%20Festivals.flac?dl=0

**Comment by orian34** [comment]
Not relevant anymore after the BGM update.
