### ISSUE TITLE
Rest of HD graphics for QA

### ISSUE THREAD

**Issue by Grelo** [07th-mod/meakashi#4]
Ok i have finished the notes and scenarios for Question Arcs. I dont know if its all because, lot of unused cgs are in the folder like MGs weird ones so i skipped some which i thought are not used. If you found some leftovers, please make a list of them so i can create them later, thanks.

https://mega.nz/#!kYshQaiA!_jhvGcrXHCJCjOPalE3z9kmsYs7HghJS5RneAFxB9Ro

P.S. Please copy file "s_jump_back" from Wata folder and put it to Hima i forgot that one.

**Comment by ItaloKnox** [comment]
Took me a while but everything is up and running, thanks a lot for finishing these. 😄
