### ISSUE TITLE
Censor line

### ISSUE THREAD

**Issue by orian34** [07th-mod/meakashi#40]
I'm pretty sure that this line only stands for the censored version, considering she speaks of being hangover in the uncensored one(and Watanagashi does separate this line for the flag).
https://github.com/07th-mod/meakashi/blob/50786324d56c39532079d1bf1b8462792ac6b2ae/Update/_meak_019_1.txt#L1716

@Norgus  do your magic 👌

**Comment by Norgus** [comment]
Thanks, looks like you're right! Fixed in the following commit:

100e4db33fda6353b2678d78486d98dbb85dd387
