### ISSUE TITLE
Game not progressing properly

### ISSUE THREAD

**Issue by Toukochan** [07th-mod/meakashi#42]
I had been re-reading Meakashi when the new patch arrived, and after installing it I was able to continue fine.  But when I got to the end of the section I finished (15_1), instead of going to 15_2, it gave me a 'save/continue' screen, then went back to 14_1.  I'm unable to move past this.

**Comment by orian34** [comment]
It might be caused by having an old save, try using the chapter skip and start the day 15. That should work correctly

**Comment by Toukochan** [comment]
Yeah, that was it.  I should know better now than to try and patch while I'm mid-game.  Thanks!

**Comment by orian34** [comment]
👌
