### ISSUE TITLE
Line in _meak_017 is duplicated from later on

### ISSUE THREAD

**Issue by tellowkrinkle** [07th-mod/meakashi#45]
Somehow this line (which is definitely not the correct translation) must have gotten copied from L253 (the bottom one) in the MG translation.  We should probably fix it.
https://github.com/07th-mod/meakashi/blob/64597fbbab881a0e7f84df99deced424415e43b6/Update/_meak_017.txt#L162-L163

https://github.com/07th-mod/meakashi/blob/64597fbbab881a0e7f84df99deced424415e43b6/Update/_meak_017.txt#L252-L253

**Comment by Norgus** [comment]
I'm not sure I did that well myself, but here y'are!
11673c5d72e624e28268d43c05a3c64b75dd8151
