### ISSUE TITLE
Updated GOG version won't boot up

### ISSUE THREAD

**Issue by thewilder** [07th-mod/meakashi#46]
As above. GOG version got updated a week ago, perhaps that might be the reason. Any help appreciated.

**Comment by ItaloKnox** [comment]
Probably the exact same reason Tata didn't work. Try this: http://07th-mod.com/rikachama/Meakashi-UI.7z

**Comment by thewilder** [comment]
Hmm, still blank screen.

**Comment by ItaloKnox** [comment]
Please post your ``output_log`` file so we can take a look.

**Comment by thewilder** [comment]
Here you go. 
[output_log.txt](https://github.com/07th-mod/meakashi/files/3085774/output_log.txt)

**Comment by ItaloKnox** [comment]
Looks like we have another issue with the UI. Is that another new version
or did we miss anything? @enumag

Em ter, 16 de abr de 2019 12:57, thewilder <notifications@github.com>
escreveu:

**Comment by enumag** [comment]
@ItaloKnox No it's not a new version. In fact it's an old version. Looks like GOG version is now different than Steam.

**Comment by ItaloKnox** [comment]
Do we have a version for it or do we need to make another one?

Em ter, 16 de abr de 2019 14:38, Jáchym Toušek <notifications@github.com>
escreveu:

**Comment by enumag** [comment]
I don't have the vanilla version of the older UI. Can you upload it?

**Comment by thewilder** [comment]
Was the last message for me perhaps?

**Comment by enumag** [comment]
@thewilder Yeah, it was. The vanilla UI should be in the game directory (`sharedassets0.assets.backup` and `sharedassets0.assets.resS.backup`).

**Comment by thewilder** [comment]
Here you go mate.
[HigurashiEp05_Data.zip](https://github.com/07th-mod/meakashi/files/3090630/HigurashiEp05_Data.zip)

**Comment by enumag** [comment]
Try this: https://www.dropbox.com/s/trqlyzczwv1i5us/Meakashi_gog_win.7z?dl=0

**Comment by thewilder** [comment]
Thanks for the hard work! It's working now, tho the menu looked a bit wobbly.

**Comment by enumag** [comment]
Is this better? https://www.dropbox.com/s/ig1n2s2mvpjox6j/Meakashi_gog_win_legacy.7z?dl=0

**Comment by thewilder** [comment]
Ye, it's perfect now. Thanks again!
