### ISSUE TITLE
Start Menu has bugged text

### ISSUE THREAD

**Issue by emandrow** [07th-mod/meakashi#48]
After booting the game the menu has glitched text (1st image). Also, when hovering the cursor on one of the options, the text changes to an incorrect version (2nd image).
![menu](https://user-images.githubusercontent.com/53008975/61382556-4b70c100-a8ad-11e9-8a1d-ec39e4b59d7f.png)
![overlay](https://user-images.githubusercontent.com/53008975/61382571-5297cf00-a8ad-11e9-931c-c12bf58d984a.png)

**Comment by ItaloKnox** [comment]
Can you post your ``output_log`` file? It's usually inside the ``HigurashiEp05_Data`` folder. If you are running Linux or Mac, it might be called ``player.log`` as well.

**Comment by emandrow** [comment]
Here it is.
[output_log.txt](https://github.com/07th-mod/meakashi/files/3402994/output_log.txt)

**Comment by ItaloKnox** [comment]
I'm not really seeing anything out of the ordinary, do you still get the same results if you run the game in fullscreen and/or windowed mode?

Also, tagging @enumag to check the UI mod.

**Comment by enumag** [comment]
Hmm that's odd. I know about this issue and I thought we had that fixed... I'll get back to you this weekend, hopefully we can fix the issue. Sorry but I can't do it sooner, I'm away for a few days now.

**Comment by enumag** [comment]
Fixed by https://github.com/07th-mod/ui-editing-scripts/commit/b66d8f70fa49fd056f8a8fbaf1efe1910fae86dc.

The fix will be a part of our next release most likely some time next week.
