### ISSUE TITLE
Missing stuff

### ISSUE THREAD

**Issue by Grelo** [07th-mod/meakashi#5]
I found out that the end credits with summary of deaths (the ones where "you" song should be playing) are missing. Is it problem on MG side or we screwed something. Plus at the end of "_meak_ep_03" are cgs i created like omake tip and stuff but in actual game they are not showing is it because they have "//" in front of them?.

**Comment by Grelo** [comment]
Ok since no one were willing to help i tried looking in to this and here it is.....

[&endroll_staff5.txt](https://github.com/07th-mod/meakashi/files/987517/endroll_staff5.txt)
[_meak_ep_02.txt](https://github.com/07th-mod/meakashi/files/987518/_meak_ep_02.txt)
[_meak_ep_03.txt](https://github.com/07th-mod/meakashi/files/987519/_meak_ep_03.txt)

**Comment by ItaloKnox** [comment]
My bad, I completely missed this issue. Can I assume these are updated?

**Comment by Grelo** [comment]
Yep.

**Comment by ItaloKnox** [comment]
Thanks, I'll upload them asap.

**Comment by ItaloKnox** [comment]
They should be already in the repo now. Sorry about that again, wasn't on purpose.
If everything goes well I'll push these into a full release sometime this week.
