### ISSUE TITLE
Issue in chapter 13 / Day 23

### ISSUE THREAD

**Issue by TraceStar** [07th-mod/meakashi#50]
Game installed on Linux Steam with 1.0.1 installer.

In chapter 13 / day 23 the screen gets stuck at the Satoshi / Satoko scene with the sky background. Right after Satoshi says "you can cry now", the playthrough gets stuck. No texts come up anymore and most interaction won't work, i.e. quicksave, quick load, menu screen skip etc. F for fullscreen works and clicking X to close the window still asks "are you sure" to exit the game. Choosing chapter jump instead of reloading game also gets the same issue.

Reinstalling does not solve the issue but changing to Ryukishi sprites at he the point where Satoshi says "you can cry now" allows the scene to be played and saving afterwards works. Switching to remake / console sprites after passing the "you can cry now" part will have Satoko stay as Ryukishi crying sprite. Satoshi can be switched to other sprites. Satoko stayed on screen until the scene changes. If game options are changed to remake / console sprites, and game is loaded at the point after "you can cry now" Satoko will not be on screen.

![Screenshot from 2019-11-20 13:57:21](https://user-images.githubusercontent.com/11336222/69212973-bf91dd00-0b9d-11ea-924a-d0a8ae283c1f.png)

![Screenshot from 2019-11-20 14:02:48](https://user-images.githubusercontent.com/11336222/69213245-768e5880-0b9e-11ea-8764-a3f5b825eaff.png)

![Screenshot from 2019-11-20 14:03:24](https://user-images.githubusercontent.com/11336222/69213267-89a12880-0b9e-11ea-9776-883d69d1248d.png)

![Screenshot from 2019-11-20 14:03:57](https://user-images.githubusercontent.com/11336222/69213291-9cb3f880-0b9e-11ea-9feb-a837e98893fe.png)

**Comment by ItaloKnox** [comment]
Can you get us your ``Player.log`` file? I believe it should be inside the game folder in Linux systems.

**Comment by enumag** [comment]
save file soon before the error might help too

**Comment by TraceStar** [comment]
It happened a bit earlier this time. Here's the log and save game.

[Player.log](https://github.com/07th-mod/meakashi/files/3867813/Player.log)

[save011.zip](https://github.com/07th-mod/meakashi/files/3867815/save011.zip)

**Comment by TraceStar** [comment]
Here's a log without exiting the game, right as it got stuck
[Player.log](https://github.com/07th-mod/meakashi/files/3867818/Player.log)

**Comment by ItaloKnox** [comment]
Looks like the sprite ``sa2a_warai_a1_0`` is missing in the console sprites folder. I checked the graphics pack and couldn't find it either. I'm not sure how this happened, but I'll look into fixing it asap.

**Comment by ItaloKnox** [comment]
Can you try extracting this file inside the root of your game folder and see if it fixes the issue?
[HigurashiEp05_Data.zip](https://github.com/07th-mod/meakashi/files/3867859/HigurashiEp05_Data.zip)

**Comment by TraceStar** [comment]
That fixed the issue for a bit. Here's the log to where it got stuck again. Seems to be another missing file `sa2a_naku_a1_0`. Renaming one of the other files to that sprite allowed the scene to be played to the end. 

[Player.log](https://github.com/07th-mod/meakashi/files/3867920/Player.log)

**Comment by ItaloKnox** [comment]
That probably means a lot of files are missing, I'll have to ask @enumag to rerun the compilation tool, so we can start from scratch. I will let you know when we push a new graphics pack.

**Comment by enumag** [comment]
Indeed we're missing quite a few sprites. Not sure how that happened. 🤔  I need to check the other chapters too...

**Comment by enumag** [comment]
Ok, Meakashi is the only bugged chapter. Looks like we messed up somewhere though I have no idea where yet.

**Comment by enumag** [comment]
Actually I had some false positives there. We're only missing a few files:

```
File CGAlt/sprite/sato1_warai_0.png not found.
File CG/sprite/sa2a_warai_a1_0.png not found.
File CG/sprite/sa2a_warai_a1_1.png not found.
File CG/sprite/sa2a_warai_a1_2.png not found.
File CG/sprite/sa2a_naku_a1_0.png not found.
File CG/sprite/sa2a_naku_a1_1.png not found.
File CG/sprite/sa2a_naku_a1_2.png not found.
File CGAlt/sprite/sa2a_naku_a1_0.png not found.
```

**Comment by orian34** [comment]
Seems to be only the transparent variants

**Comment by enumag** [comment]
but only some of them which doesn't make much sense

**Comment by enumag** [comment]
Fixes in https://github.com/07th-mod/meakashi/releases/tag/v4.8.1. Thanks for reporting!
