### ISSUE TITLE
Fullscreen set by height, not width

### ISSUE THREAD

**Issue by Maelstrom1** [07th-mod/meakashi#6]
<img width="960" alt="screenshot 2017-05-11 18 48 49" src="https://cloud.githubusercontent.com/assets/20371049/25975191/f0d05d24-367a-11e7-9b11-c8b2e257c5de.png">
As you can see, my weird computer has a different screen size, but the patch fit it by height, not width, so I have this wonderful lack of space on either side. This wasn't the case with Umineko, where I got black bars on the top and bottom. Idk what's causing this, but it's preventing me from wanting to say in full-screen mode.

**Comment by ItaloKnox** [comment]
See if you have a file called ``init.txt`` inside your Update folder. If you have it, try looking for this line: ``SetWindowSize(1280, 720);``

Supposing you found it, I suggest you to clean the CompiledScriptsUpdate folder and then try opening the game again. If you didn't find it, [try downloading the latest patch](https://github.com/07th-mod/meakashi/releases/latest) and manually extracting it inside your game folder. Don't forget to clean the CompiledScriptsUpdate folder.

**Comment by ItaloKnox** [comment]
Oh, wait a second, it does work windowed but it doesn't add black bars when running in fullscreen because of your screen resolution?

**Comment by Maelstrom1** [comment]
^This. I just downloaded the stuff today, so it should be the latest version.

**Comment by ItaloKnox** [comment]
Well, if it works fine windowed but gets stretched in fullscreen, then there's nothing we can do. It's a engine issue and our control over it is pretty basic.

My suggestion is to try a borderless windowed tool to see if it fixes the issue.

**Comment by DoctorDiablo** [comment]
You might be able to get it rendering correctly by changing the desktop settings for your video card.  Make sure the scaling mode is set to aspect ratio and scaling is performed on Display.

![image](https://cloud.githubusercontent.com/assets/20390474/26015274/6701a4c2-372e-11e7-9c48-b1d547bb29c6.png)

**Comment by enumag** [comment]
@Maelstrom1 Did you manage to solve the issue?

**Comment by Maelstrom1** [comment]
I gave up and played it on windowed. Also, I got a new computer that has a proper screen ratio, so this won't be a problem again. No, I never actually tried this. Laziness won out

**Comment by enumag** [comment]
Understood. Have fun!
