### ISSUE TITLE
Black screen during endroll

### ISSUE THREAD

**Issue by pmrowla** [07th-mod/meakashi#7]
The endroll staff/death credits never actually plays, it just shows a black screen for the whole duration.

@marakeusz comment from https://github.com/07th-mod/meakashi/commit/3b985b54b297493d84d0044bc9bf63d6d0159c26#commitcomment-22115574 is correct, if you rename endroll_staff5.txt with an ampersand to match the script the endroll scene will play correctly.

**Comment by ItaloKnox** [comment]
Thanks for the heads-up, I just pushed a fix even though I thought this would happen but our graphics modder said it was correct.....

A patch correcting this issue should be out soon. Thanks a lot. 👍
