### ISSUE TITLE
Typo in image

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/meakashi#72]
Sunny is spelled wrong on this image in Meakashi.

![image](https://user-images.githubusercontent.com/20390474/106403193-55a8d080-63fb-11eb-85f7-330ff715c42d.png)

**Comment by jroyvde** [comment]
I've manually edited a fixed version of this image (nort5.png), as well as two others with similar typos (meaed3.png and nort43.png), uploaded here for potential addition to the graphics archive: https://drive.proton.me/urls/PH4GWFEVVR#wO9s99XLYpk3

nort5.png:        'suny day' -> 'sunny day'
meaed3.png:   'been tremendously long one' -> 'been a tremendously long one'
nort43.png:      'done by human being' -> 'done by human beings'

@drojf As requested :)

**Comment by jroyvde** [comment]
There are some more text CGs I've noticed with more complex errors (two grammar mistakes in the last line of meaed4.png, and the continuity mistake in 58b.png raised in #44) that I'd like to have a go at fixing later, though it would be ideal if I could get my hands on the source files (Photoshop .psd, GIMP .xcf, or equivalent) to make things simpler and cleaner.

**Comment by drojf** [comment]
> it would be ideal if I could get my hands on the source files (Photoshop .psd, GIMP .xcf, or equivalent) to make things simpler and cleaner.

I've added a page to the dev wiki https://07th-mod.com/wiki/developer/graphics/psd-files-templates/

If you download https://07th-mod.com/archive/Higurashi-MixedFiles-PSD.7z, then check the folder `UI and Text Images/translation_psds/might be useful`, I think those are the PSD files for the text images?

But I don't have a proper photoshop installed so I'm not sure if they are the right files, let me know if they are usable or not.

**Comment by drojf** [comment]
I've updated the archive https://07th-mod.com/rikachama/og-dll-asset-update/meakashi-og-dll-asset-update.7z with the images, so this should be fixed now.

Please comment on #44 to followup the .psd files etc. instead of this issue or on Discord
