### ISSUE TITLE
Crash on startup: HigurashiEp05.x86_64: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

### ISSUE THREAD

**Issue by mvbs23** [07th-mod/meakashi#78]
The problem: The game crashes on startup.

Reproduction Instructions: Launching the game, the dark blue of the game appears for about 3 seconds, and immediately crashes.

Mod/Game history: I had this issue some hours into the game; I tried reintalling the original game in a new location (fresh install), then I installed the mod.

Save information: None at all.

Does the unmodded game have the same problem?: No, I tried launching it unmodded once and it worked.

The game: Higurashi Ch.5.

The mod variant: ADV.

I bought the game at: GOG.

My operating system is: Linux (Manjaro).

I installed the base game: Yesterday.

I installed the mod: Using the Installer.

Mod Download and Install Date: Installed yesterday.

Mod Options: None.

State anything "special" about your computer's setup: Laptop from 8 years ago.

State if you've changed anything to try and fix the problem: I tried re-installing the game and the mod, and cleared my saves. I also tried reinstalling my OS, just in case.

State if anything has changed recently on your PC: Normal updates of software; everything is up-to-date.

[MOD-INSTALLER-LOG-2021-10-03_01-05-12.txt](https://github.com/07th-mod/meakashi/files/7273633/MOD-INSTALLER-LOG-2021-10-03_01-05-12.txt)

[Player.log](https://github.com/07th-mod/meakashi/files/7273638/Player.log)

**Comment by drojf** [comment]
Hi, I'm not really sure what would cause this problem. I did some googling and couldn't get a definitive answer. 

There are some answers about permissions, so you can double check the executable has the `+x` permission (I don't see how you could launch it without the +x permission, like here: https://stackoverflow.com/a/18144303/848627), but I'm not sure what else to check other than that.

I also saw exactly one issue where the user fixed it by updating their graphics driver: https://forum.paradoxplaza.com/forum/threads/cities-skylines-steam-game-wont-launch-linux.1484750/

You could also try installing Ubuntu 20.04, if you're willing to go as far as re-installing your OS. We've had reports (and I've played a little bit of one chapter) that 20.04 works OK with this game/our mod: https://github.com/07th-mod/higurashi-patch-compiler/issues/58#issuecomment-932833986 . The main issue we've had in the past with linux is when using the GNOME window manager, but I don't think this applies here (see the thread in the link).

I realize that I'm assuming this issue is OS related and not mod related, but it's because I don't really know how to even go about fixing this if the issue was related to the mod.

**Comment by mvbs23** [comment]
Hi. I tried with the two first options: it seems to be neither of them. I also tried downgrading the linux kernel to a more stable one, but that didn't do the trick. I'm considering the change of OS, but as a last resort (If I can ask: what desktop/envieronment seems to work best with the mod?).

Something happened too:

I kept trying to start it around 30 times in a row, deleting each time the ~/unity3d/MangaGamer/ folder, wondering if it had something to do with randomness. And it finally worked once, surprisingly. It kept open for about 30 seconds and started, although somewhat more FPS-slow than the first time I played before this issue.

I tried again with the folder I saved from my saves. After dozens of times I gave up and tried bringing up only the savefiles without the global.dat, Player.log and prefs files. After several crashes, it worked again, this time with the saves there.

I looked up to Player.log generated by this time, and it changed. I hope it works to reveal  the issue here.

[Player.log](https://github.com/07th-mod/meakashi/files/7274908/Player.log)

**Comment by drojf** [comment]
> If I can ask: what desktop/envieronment seems to work best with the mod?

I *think* it's Ubuntu 20.04 and XFCE, although if you're using Ubuntu 20.04 the default desktop environment should work fine

----

I had a look at the log and the main wierd stuff I see is related to graphics/x window system, but I don't really know what it means.

```
Desktop is 1366 x 768 @ 60 Hz
XError: GLXBadFBConfig (error 167, opcode 152/0, serial 60, XID 05800008, display 0x22c2010
XError: GLXBadFBConfig (error 167, opcode 152/0, serial 64, XID 05800009, display 0x22c2010
XError: GLXBadFBConfig (error 167, opcode 152/0, serial 68, XID 0580000a, display 0x22c2010
```

There's also a message about level0 being corrupted, but I think that isn't related / not something to worry about.

```
The file '/home/mau/GOG Games/Higurashi When They Cry Hou Ch 5 Meakashi/game/HigurashiEp05_Data/level0' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
```

----

The fact that the game randomly launches very occasionally makes me think that this will be too difficult to fix unfortunately...I would suspect it's either your OS configuration, or the fact that you're running on older hardware. You've already tried most of the things I would tell you to try, except for changing to Ubuntu 20.04 (which might not even fix the problem).

Now that I think about it, you could just boot Ubuntu 20.04 off a USB, then launch the game by finding it on your HDD (well, you might need to mount your hdd). Then you could check whether that fixes the problem without installing Ubuntu.

----

I'm guessing chapters 1-4 worked fine, it's just chapter 5 which has this problem?

**Comment by mvbs23** [comment]
Hi. It's a really good idea the one of the Live USB, although I couldn't start the game at all (maybe I didn't know how to properly execute it from the terminal).

So I installed Ubuntu in the HDD, and then installed the game and the mod in the new OS.

Unfortunately this results in a similar issue: although it starts and doesn't crash like in Manjaro, it gets frozen/stuck either with the starting blue screen or in the opening selection menu of BGM.

I tried several times (as previously) and it finally started as that lucky times in the previous OS. The Player.log is identical to the previous one.

Could this be then a hardware related issue?

And yes: Chapters 1-4 worked flawlessly.

**Comment by mvbs23** [comment]
I had a hunch, and started the game unmodded again. Last time I did it, it ran well the first time so I assumed it had nothing to do with the original game. But I was wrong, it was just one of those lucky times; it appears to be that the installer is at fault: it's the same issue unmodded.

The GOG Linux installer has to be the issue. Although the game can start after a few tries, it's by all means faulty.

Sorry for my mistake. I will contact the support team on GOG.

**Comment by enumag** [comment]
Not GOG, you should contact MangaGamer.

**Comment by ItaloKnox** [comment]
> 
> 
> Not GOG, you should contact MangaGamer. Well unless the GOG's installer messed it up. 🤔

GOG Installers are handled by GOG themselves, so if the installer is the issue, it should be reported to them instead. I think there's nothing MangaGamer can do about it (unless they can directly fix it with GOG?)

**Comment by mvbs23** [comment]
I tried borrowing another PC (although with Linux too), and it gave me the same result. The game unmodded started successfully the first time, but then it's all the same with getting stuck at the beginning or crashing.

Has someone with the MangaGamer Linux version had have some similar issue? Or with the GOG Linux version? I tried searching for it in the project related issues but found nothing so specifically.

I already opened a submission on GOG. But I have no way to know if it's the same with the MG installer, do I?

**Comment by drojf** [comment]
> Has someone with the MangaGamer Linux version had have some similar issue? Or with the GOG Linux version?

I don't think I've ever seen this issue reported before (by anyone), so I'm surprised you tried it on a different computer and you still had the issue...

**Comment by mvbs23** [comment]
Hi.

I contacted both support teams from GOG and MG. It doesn't seem to be an issue easy to find out the cause of it. It also affects the Tsumihoroboshi release.

I'm closing the issue because it has nothing to do with the mod in the first place. Thank you for your help.
