### ISSUE TITLE
Not able to switch between Mangagamer and Alchemist Sprites

### ISSUE THREAD

**Issue by LunaticSpark** [07th-mod/meakashi#8]
Not by using the in game menu or with the shortcut (p). Is this intended? I like the CG events from the ps3 version but I want to keep the mangagamer sprites.

**Comment by ItaloKnox** [comment]
Not at all, I just tried it and seems to work fine here. Did you manually install the patch or used the installer?

**Comment by LunaticSpark** [comment]
I manually installed and followed the installation guide except for not replacing the original backgrounds in the CG folder.

**Comment by LunaticSpark** [comment]
Ok so thanks to your comment I reinstalled using the installer and the switching between Mangagamer and Alchemist worked fine. I then replaced the CG folder with the copy of the old CG folder I made and then filled in the cut-in stuff from Alchemist, and now I also have the original backgrounds and the switching still works.

It seems the problem may have been in the "Update" folder provided in the manual installation. Thanks so much for the quick reply!

**Comment by ItaloKnox** [comment]
I actually think you just forgot to install the MangaGamer sprites, the Update folder shouldn't influence sprites (actually the game wouldn't display most of the sprites if it wasn't there) but at least you got it to work. If you need anything else, just reopen this issue!
