### ISSUE TITLE
Missing voices

### ISSUE THREAD

**Issue by enumag** [07th-mod/meakashi#9]
@ItaloKnox There seem to be some missing voices in this [section](https://github.com/07th-mod/meakashi/blob/master/Update/_meak_015_1.txt#L790-L833). `s06/01/150100048` is used, then no voices for several lines and then `s06/01/150100054`. Looks like voices 49-53 should be added somewhere in there. Can you do it? I'm lost here without understanding japanese.

EDIT:
`s06/01/150100056` and `s06/01/150100058` are also missing (58 is only among PS2 voices).
`s06/01/150100057` doesn't seem to match the line where it was added so I commented it out.

**Comment by ItaloKnox** [comment]
Oh, I think I said something about this issue before. The thing is: we have no voices for this scene and the PS2 voices are also censored. If I recall correctly, the script just skips these lines and call it a day. I'm not really sure about what we should do.

**Comment by ItaloKnox** [comment]
Double posting because you might have seen the reply. 

This one wasn't skipped, I just got it wrong. Give me a couple minutes to check and fix it.

**Comment by ItaloKnox** [comment]
Huh, nope, I don't think we can fix it without translating. It was pretty much censored and the voices don't really fit in.

I'm not feeling all that well today (feels like everything is going too fast), so I'm sorry for the confusion. I'll see if I can translate it later, but honestly I wouldn't like to censor the text.

**Comment by enumag** [comment]
Personally in cases like this where the censored part is replaced with different lines rather than just outright skipped I usually prefer the censored but voiced version. I mean we're trying to port Sui so it's probably best to keep as many voices as possible.

**Comment by enumag** [comment]
But of course it's up to you. Also take as much time as you need to recover, There are some fixes I need to do in this section but I have more than plenty of other things to fix elsewhere so no rush.

**Comment by Grelo** [comment]
Just dont censor text please. Everything but that.

**Comment by enumag** [comment]
So... leave as is then? @ItaloKnox Just tell me your verdict if you want to do something about this or not.

**Comment by ItaloKnox** [comment]
I think we should leave it uncensored, at least for now. I'm not satisfied with my translation so we should stick to the higher quality text and since it's just a very small part, I think it's not such a big issue.

Let's revisit this in the future.

**Comment by enumag** [comment]
Ok. I'll leave the issue open and move on to the other issues in the script. Thanks.

**Comment by enumag** [comment]
@ItaloKnox Is [this voice](https://www.dropbox.com/s/2v49lfqv7uonset/150100058.ogg?dl=0) (from PS2) good for [this line](https://github.com/07th-mod/meakashi/blob/master/Update/_meak_015_1.txt#L951-L952)?

**Comment by ItaloKnox** [comment]
It ends the same but it is completely different. There's no much stuff going on there that I can only read but not understand a thing, actually. lol

**Comment by Norgus** [comment]
Added the files in, some of them only appearing if you have the censorship set relatively high (4/5).
I allowed similar lines to play in the uncensored version.

https://github.com/07th-mod/meakashi/commit/ba4ad2cb0f21c8ab95372af492de335824800531
